version: '3.8'

services:
  bot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - CHANNEL_ID=${CHANNEL_ID}
      - FORCE_SUB_CHANNEL_1=${FORCE_SUB_CHANNEL_1}
      - FORCE_SUB_CHANNEL_2=${FORCE_SUB_CHANNEL_2}
      - FORCE_SUB_CHANNEL_3=${FORCE_SUB_CHANNEL_3}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME:-file_sharing_bot}
      - PROTECT_CONTENT=${PROTECT_CONTENT:-True}
      - AUTO_DELETE_TIME=${AUTO_DELETE_TIME:-3600}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb_data: